version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: mpire-docker
    container_name: sites
    ports:
      - 80:80
    volumes:
      - .:/var/www
    links:
      - mysql
    environment:
      DB_HOST: mysql
    networks:
      - mpire_network

  mysql:
    image: mysql:5.7
    container_name: database
    ports:
      - 13306:3306
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql:cached
    networks:
      - mpire_network

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - 7005:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    networks:
      - mpire_network

volumes:
  db_data:

networks:
  mpire_network:
